apiVersion: batch/v1
kind: CronJob
metadata:
  name: kakao-consumer
  namespace: data-mgt
spec:
  schedule: "20,50 * * * *" # 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 1000
      template:
        spec:
          containers:
          - name: kakao-consumer
            image: aam411/k8skakaoconsumer:3.0
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
