# soup-mysql-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: soup-mysql-pv
  labels:
    type: rdb
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/soup-mysql-storage/"