apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: rdb
  name: soup-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      type: rdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        type: rdb
    spec:
      containers:
      - image: mysql:5.7-debian
        name: soup-mysql
        args:
        - --character-set-server=utf8
        - --collation-server=utf8_general_ci
        - --explicit_defaults_for_timestamp=1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass123#
        - name: MYSQL_DATABASE
          value: soup
        - name: MYSQL_ROOT_HOST
          value: '%'
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: tz-seoul
          mountPath: /etc/localtime
        - name: soup-mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: tz-seoul
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
      - name: soup-mysql-storage
        persistentVolumeClaim:
          claimName: soup-mysql-pvc
