apiVersion: batch/v1
kind: CronJob
metadata:
  name: street-consumer
spec:
  schedule: "20,50 * * * *" # 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 1000
      template:
        spec:
          containers:
          - name: street-consumer
            image: aam411/k8sstreetconsumer:3.1
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
