apiVersion: v1
kind: Service
metadata:
  name: soup-backend
  labels:
    type: backend
spec:
  type: NodePort
  selector:
    type: backend
  ports:
  - protocol: 'TCP'
    port: 8000
    targetPort: 8000

